<a href="https://colab.research.google.com/github/AMANVISHWAKARMA27/Machine-Learning/blob/main/numpyLibrary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
myList = [1,2,3]
arr = np.array(myList) #array of rank 1
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
myList1 = [1,2,3]
myList2 = [4,5,6]
myList3 = [7,8,9]
a = np.array([myList1,myList2,myList3]) #array of rank 2
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#another way of reating an array
b = np.array([[1,2,3,4], [5,6,7,8], [-1,-5,-7,-9],[3,-5,-4,-1]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-1, -5, -7, -9],
       [ 3, -5, -4, -1]])

Accessing the elements of an array using
Indices

In [ ]:
b[0:2, 0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-1, -5, -7, -9],
       [ 3, -5, -4, -1]])

When we use the slicing method, (a:b, c:d), if we define all a,b,c,d then rows are selected from a to (b-1) and columns from c to (d-1). In case we do not define any of a,b,c,d then all that particular elements are included.

So here, we define three things;
( start : end : steps)

In [ ]:
b[ : , :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-1, -5, -7, -9],
       [ 3, -5, -4, -1]])

In [ ]:
b[1:4,1:4]

array([[ 6,  7,  8],
       [-5, -7, -9],
       [-5, -4, -1]])

In [ ]:
b[:2, ::2]
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-1, -5, -7, -9],
       [ 3, -5, -4, -1]])

Operations on array

In [ ]:
#Adding some number to each element of an array
print(b+1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [ 0 -4 -6 -8]
 [ 4 -4 -3  0]]


In [ ]:
#Subtracting some number from each element of an array
print(b-2)

[[ -1   0   1   2]
 [  3   4   5   6]
 [ -3  -7  -9 -11]
 [  1  -7  -6  -3]]


In [ ]:
#sum of all array elements
a.sum()

45

In [ ]:
#Adding two different arrays
a = ([[1,2,3],[4,5,6]])
b = ([[-1,-2,-3],[-4,-5,-6]])
a+b

[[1, 2, 3], [4, 5, 6], [-1, -2, -3], [-4, -5, -6]]

In [ ]:
type(a)

list

In [ ]:
arr = np.array( [[1, 2, 3],
                 [4, 5, 6]])

print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim) #prints dimension of an array
print(arr.shape) #shape of array
print(arr.size) #number of elements in an array
print(arr.dtype) #type of elements in an array

2
(2, 3)
6
int64


In [ ]:
#Array initialized with all zeros and size 3*4 = 12
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#An array having type complex and all elements being constant
d = np.full((3,3), 6, dtype = 'complex')
d

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [ ]:
#A random array
e = np.random.random((2, 2))
e

array([[0.41721847, 0.67113707],
       [0.80732619, 0.6011678 ]])

In [ ]:
#A sequential array
#arange(start, end, steps)

f = np.arange(0, 30, 2)
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
#an array with 10 values between 0 and 5
#linspace( start, end, elements)
g = np.linspace(0, 5, 10)
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
arr = np.array([[1,2,3,4],
                [-3,4,-5,6],
                [1,0,8,9]])
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4, -3,  4]],

       [[-5,  6,  1],
        [ 0,  8,  9]]])

In [ ]:
arr.flatten() #flat the array

array([ 1,  2,  3,  4, -3,  4, -5,  6,  1,  0,  8,  9])

In [ ]:
x = np.array([1, 2])
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.0, 2.0])
x.dtype

dtype('float64')

In [ ]:
x = np.array([1.0,2.0] , dtype = np.int64)
x.dtype

dtype('int64')