<a href="https://colab.research.google.com/github/AMANVISHWAKARMA27/Machine-Learning/blob/main/Pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame( np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3'
, 'Row4', 'Row4'] , columns = ["column1", "column2", "column3", "column4"])

In [ ]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
df.to_csv('Test1.csv')

In [ ]:
#Accessing the elements from dataframe
#1. loc (any index location)    2. iloc (integer index location)

df.loc['Row1']

column1    0
column2    1
column3    2
column4    3
Name: Row1, dtype: int64

In [ ]:
type(df.loc['Row1'])

pandas.core.series.Series

In [ ]:
df.iloc[0:3 , 0:2]

column1  column2
Row1        0        1
Row2        4        5
Row3        8        9

from matplotlib import pyplot as plt
_df_15['column1'].plot(kind='hist', bins=20, title='column1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_16['column2'].plot(kind='hist', bins=20, title='column2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17.plot(kind='scatter', x='column1', y='column2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column1']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column1'}, axis=1)
              .sort_values('column1', ascending=True))
  xs = counted['column1']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_18.sort_values('column1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column1')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column2']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column2'}, axis=1)
              .sort_values('column2', ascending=True))
  xs = counted['column2']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_19.sort_values('column2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column2')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_20['column1'].plot(kind='line', figsize=(8, 4), title='column1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_21['column2'].plot(kind='line', figsize=(8, 4), title='column2')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
type(df.iloc[0:3 , 0:2])

pandas.core.frame.DataFrame

In [ ]:
#converting the datafram einto an array
df.iloc[:4 , 1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
df.iloc[: , :].values.shape

(5, 4)

In [ ]:
df['column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: column1, dtype: int64

In [ ]:
df['column1'].unique()

array([ 0,  4,  8, 12, 16])

Creating a Pandas DataFrame

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#list of strings
list = ['Aman', 'Ansh','Ayush', 'Maneesh', 'Rishi']
pd.DataFrame(list)

0
0     Aman
1     Ansh
2    Ayush
3  Maneesh
4    Rishi

In [ ]:
#Dictionary of ndarray/lists
data = {'Name':['Aman','Ansh','Ayush','Siddhant'], 'Roll No':[32,21,49,12], 'Age':[19,18,16,19]}
pd.DataFrame(data)

Name  Roll No  Age
0      Aman       32   19
1      Ansh       21   18
2     Ayush       49   16
3  Siddhant       12   19

In [ ]:
pd.DataFrame(data)[['Name','Roll No']]

Name  Roll No
0      Aman       32
1      Ansh       21
2     Ayush       49
3  Siddhant       12

In [ ]:
df = pd.DataFrame(data)
df

Name  Roll No  Age
0      Aman       32   19
1      Ansh       21   18
2     Ayush       49   16
3  Siddhant       12   19

In [ ]:
data = pd.read_csv("nba.csv", index_col = "Name")
print(data)

                         Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                          

In [ ]:
#Row selection using loc[] function
data.loc["Avery Bradley"]

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

In [ ]:
data.loc["R.J. Hunter"]

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

In [ ]:
data.drop(["Team","Weight"], axis = 1, inplace = True)
#axis = 1 means column is to be dropped
#axis = 0 means row is to be dropped.
data

Number Position   Age Height            College     Salary
Name                                                                     
Avery Bradley     0.0       PG  25.0    6-2              Texas  7730337.0
Jae Crowder      99.0       SF  25.0    6-6          Marquette  6796117.0
John Holland     30.0       SG  27.0    6-5  Boston University        NaN
R.J. Hunter      28.0       SG  22.0    6-5      Georgia State  1148640.0
Jonas Jerebko     8.0       PF  29.0   6-10                NaN  5000000.0
...               ...      ...   ...    ...                ...        ...
Shelvin Mack      8.0       PG  26.0    6-3             Butler  2433333.0
Raul Neto        25.0       PG  24.0    6-1                NaN   900000.0
Tibor Pleiss     21.0        C  26.0    7-3                NaN  2900000.0
Jeff Withey      24.0        C  26.0    7-0             Kansas   947276.0
NaN               NaN      NaN   NaN    NaN                NaN        NaN

[458 rows x 6 columns]

In [ ]:
data = pd.read_csv("nba.csv")
print(data)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Ma

In [ ]:
#Retrieving Row using iloc[] function
data.iloc[1]

Name           Jae Crowder
Team        Boston Celtics
Number                99.0
Position                SF
Age                   25.0
Height                 6-6
Weight               235.0
College          Marquette
Salary           6796117.0
Name: 1, dtype: object

In [ ]:
data = pd.read_csv("nba.csv", index_col = "Name")
print(data)

                         Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                          

In [ ]:
data.loc["Avery Bradley":"Isaiah Thomas"]
#Prints all the rows between the two defined indices inclusively.

Team  Number Position   Age Height  Weight  \
Name                                                                    
Avery Bradley    Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder      Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland     Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter      Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko    Boston Celtics     8.0       PF  29.0   6-10   231.0   
Amir Johnson     Boston Celtics    90.0       PF  29.0    6-9   240.0   
Jordan Mickey    Boston Celtics    55.0       PF  21.0    6-8   235.0   
Kelly Olynyk     Boston Celtics    41.0        C  25.0    7-0   238.0   
Terry Rozier     Boston Celtics    12.0       PG  22.0    6-2   190.0   
Marcus Smart     Boston Celtics    36.0       PG  22.0    6-4   220.0   
Jared Sullinger  Boston Celtics     7.0        C  24.0    6-9   260.0   
Isaiah Thomas    Boston Celtics     4.0       PG  27.0    5-9   185.0   

                           College      Salary  
Name                                            
Avery Bradley                Texas   7730337.0  
Jae Crowder              Marquette   6796117.0  
John Holland     Boston University         NaN  
R.J. Hunter          Georgia State   1148640.0  
Jonas Jerebko                  NaN   5000000.0  
Amir Johnson                   NaN  12000000.0  
Jordan Mickey                  LSU   1170960.0  
Kelly Olynyk               Gonzaga   2165160.0  
Terry Rozier            Louisville   1824360.0  
Marcus Smart        Oklahoma State   3431040.0  
Jared Sullinger         Ohio State   2569260.0  
Isaiah Thomas           Washington   6912869.0

In [ ]:
data = pd.read_csv("nba.csv")
print(data)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Ma

In [ ]:
data.head(10)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8   Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   
9   Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5                NaN  12000000.0  
6                LSU   1170960.0  
7            Gonzaga   2165160.0  
8         Louisville   1824360.0  
9     Oklahoma State   3431040.0

In [ ]:
newRow = pd.DataFrame({'Name':'Aman', 'Team':'Boston Celitics', 'Number':3,
                       'Position':'PG','Age':'33','Height':'6.2',
                       'Weight':'189','College':'MIT','Salary':99999},
                      index = [0])

data = pd.concat([newRow, data]).reset_index(drop = True)
data.head(5)

Name             Team  Number Position   Age Height Weight  \
0           Aman  Boston Celitics     3.0       PG    33    6.2    189   
1  Avery Bradley   Boston Celtics     0.0       PG  25.0    6-2  180.0   
2    Jae Crowder   Boston Celtics    99.0       SF  25.0    6-6  235.0   
3   John Holland   Boston Celtics    30.0       SG  27.0    6-5  205.0   
4    R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5  185.0   

             College     Salary  
0                MIT    99999.0  
1              Texas  7730337.0  
2          Marquette  6796117.0  
3  Boston University        NaN  
4      Georgia State  1148640.0

In [ ]:
newBow = pd.DataFrame({'Name':'Saloni', 'Team':'Boston Celithics','Number':4,
          'Position':'SG','Age':30,'Height':'5.5','Weight':'160',
          'College':'Colombia University','Salary':99999},
          index = [1])

data = pd.concat([newBow, data]).reset_index(drop = True)
data.head(6)


Name              Team  Number Position Age Height Weight  \
0  Saloni  Boston Celithics     4.0       SG  30    5.5    160   
1  Saloni  Boston Celithics     4.0       SG  30    5.5    160   
2  Saloni  Boston Celithics     4.0       SG  30    5.5    160   
3  Saloni  Boston Celithics     4.0       SG  30    5.5    160   
4  Saloni  Boston Celithics     4.0       SG  30    5.5    160   
5    Ansh  Boston Celithics     4.0       SG  30    5.5    160   

               College   Salary  
0  Colombia University  99999.0  
1  Colombia University  99999.0  
2  Colombia University  99999.0  
3  Colombia University  99999.0  
4  Colombia University  99999.0  
5  Colombia University  99999.0

In [ ]:
newBow = pd.DataFrame({'Name':'Saloni', 'Team':'Boston Celithics','Number':4,
          'Position':'SG','Age':19,'Height':'5.3','Weight':'58',
          'College':'Colombia University','Salary':99999},
          index = [1])

data = pd.concat([newBow, data]).reset_index(drop = True)
data.head(1)

Name              Team  Number Position Age Height Weight  \
0  Saloni  Boston Celithics     4.0       SG  19    5.3     58   

               College   Salary  
0  Colombia University  99999.0

CONVERTING DATAFRAME BACK INTO NUMPY ARRAYS

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
], columns=['a','b','c'])

arr = df.to_numpy()
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr = df[['a','c']].to_numpy()
arr

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [ ]:
#using a csv file

data = pd.read_csv("nba.csv")
#Below syntax line drops any row having some value missing.
data.dropna(inplace=True)
df = pd.DataFrame(data['Weight'].head()) #created DataFrame from weight column
df.to_numpy() #converting into numpy array.


array([[180.],
       [235.],
       [185.],
       [235.],
       [238.]])

In [ ]:
import pandas as pd
import numpy as np

excel_file = pd.ExcelFile('sheet.xlsx')
excel_file

['Sheet1']